services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inno-dashboard
      POSTGRES_PASSWORD: inno-dashboard
      POSTGRES_DB: inno-dashboard
    ports:
      - "15432:5432"
    volumes:
      - ./development/db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inno-dashboard
      SPRING_DATASOURCE_USERNAME: inno-dashboard
      SPRING_DATASOURCE_PASSWORD: inno-dashboard
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/canvas_dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"