services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inno-dashboard
      POSTGRES_PASSWORD: inno-dashboard
      POSTGRES_DB: inno-dashboard
    ports:
      - "15432:5432"
    volumes:
      - ./prod/db:/docker-entrypoint-initdb.d

  backend:
    image: ghcr.io/Overgrown9363/inno_canvas_dashboard-backend:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inno-dashboard
      SPRING_DATASOURCE_USERNAME: inno-dashboard
      SPRING_DATASOURCE_PASSWORD: inno-dashboard
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/Overgrown9363/inno_canvas_dashboard-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"