services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inno-dashboard
      POSTGRES_PASSWORD: inno-dashboard
      POSTGRES_DB: inno-dashboard
    ports:
      - "15432:5432"
    volumes:
      - ./prod/db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inno-dashboard
      SPRING_DATASOURCE_USERNAME: inno-dashboard
      SPRING_DATASOURCE_PASSWORD: inno-dashboard
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.inno-dashboard.duckdns.org`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ./frontend/canvas_dashboard
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`inno-dashboard.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=5050"
