services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inno-dashboard
      POSTGRES_PASSWORD: inno-dashboard
      POSTGRES_DB: inno-dashboard
    ports:
      - "15432:5432"
    volumes:
      - ./development/db:/docker-entrypoint-initdb.d

  static-service:
      build: ./src/test-data/courses
      ports:
        - "5000:80"