name: Build on GitHub and deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    # ---- RUNS ON GITHUB ----
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

        # ---- SETUP LOWERCASE OWNER ----
      - name: Get lowercase repository owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        # ---- BUILD REQUIREMENTS ----
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant gradlew permissions
        run: chmod +x ./gradlew

        # ---- TEST BACKEND ----
      - name: Run backend tests
        run: ./gradlew test --no-daemon

        # ---- BUILD BACKEND IMAGE ----
      - name: Build backend image
        run: |
          docker build \
            -f Dockerfile \
            -t ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-backend:latest \
            .

        # ---- BUILD FRONTEND IMAGE ----
      - name: Build frontend image
        run: |
          docker build \
            -f frontend/canvas_dashboard/Dockerfile \
            --build-arg VITE_AUTH_URL="${{ vars.VITE_AUTH_URL }}" \
            --build-arg VITE_LOGOUT_URL="${{ vars.VITE_LOGOUT_URL }}" \
            -t ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-frontend:latest \
            frontend/canvas_dashboard

        # ---- LOGIN TO GHCR ----
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # ---- PUSH IMAGES ----
      - name: Push images
        run: |
          docker push ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-backend:latest
          docker push ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-frontend:latest

  deploy:
    # ---- RUNS ON SERVER ----
    runs-on: self-hosted
    needs: build
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

        # ---- SETUP LOWERCASE OWNER ----
      - name: Get lowercase repository owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        # ---- LOGIN TO GHCR ----
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
        # ---- PULL IMAGES ----
      - name: Pull images
        run: |
          docker pull ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-backend:latest
          docker pull ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-frontend:latest
        
        # ---- MAKE SECRETS AVAILABLE ----
      - name: Write secrets to .env file
        run: |
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" > .env
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> .env
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> .env
          echo "APP_HOME_FRONTEND_REDIRECT_URL=${{ vars.APP_HOME_FRONTEND_REDIRECT_URL }}" >> .env

        # ---- START CONTAINERS ----
      - name: Start containers
        run: |
          docker compose -f docker-compose.prod.yml up -d --remove-orphans