name: Deploy to server

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    # ---- RUNS ON SERVER ----
    runs-on: self-hosted
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

        # ---- SETUP LOWERCASE OWNER ----
      - name: Get lowercase repository owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        # ---- LOGIN TO GHCR ----
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
        # ---- PULL IMAGES ----
      - name: Pull images
        run: |
          docker pull ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-backend:latest
          docker pull ${{ env.REGISTRY}}/${{ env.REPO_OWNER_LOWERCASE }}/inno_canvas_dashboard-frontend:latest
        
        # ---- MAKE SECRETS AVAILABLE ----
      - name: Write secrets to .env file
        run: |
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" > .env
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> .env
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> .env

        # ---- START CONTAINERS ----
      - name: Start containers
        run: |
          docker compose -f docker-compose.prod.yml up -d --remove-orphans